sonar.projectKey=Chaithanyanallamothu_Chay-Enterprise-Azure-DevSecOps-Platform
sonar.organization=chaithanyanallamothu
sonar.projectName=Chay Enterprise Azure DevSecOps Platform

sonar.sources=application/src
sonar.tests=application/tests

sonar.python.coverage.reportPaths=application/coverage.xml

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/__pycache__/**,**/.venv/**,**/.pytest_cache/**,**/.ruff_cache/**
sonar.coverage.exclusions=application/tests/**
