apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chay-demo-api
  namespace: argocd
spec:
  project: chay-enterprise-devsecops

  source:
    repoURL: https://github.com/Chaithanyanallamothu/Chay-Enterprise-Azure-DevSecOps-Platform.git
    targetRevision: main
    path: helm/chay-demo-api

  destination:
    server: https://kubernetes.default.svc
    namespace: chay-devsecops

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
