apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: chay-enterprise-devsecops
  namespace: argocd
spec:
  description: GitOps boundary for the Chay Enterprise Azure DevSecOps Platform

  sourceRepos:
    - https://github.com/Chaithanyanallamothu/Chay-Enterprise-Azure-DevSecOps-Platform.git

  destinations:
    - namespace: chay-devsecops
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
      name: chay-devsecops

  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment
    - group: ""
      kind: Service
