apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      automountServiceAccountToken: false

      securityContext:
        runAsNonRoot: true
        runAsUser: 472
        runAsGroup: 472
        fsGroup: 472
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: grafana
          image: grafana/grafana:11.6.0
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 3000

          env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: "Viewer"
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              value: "true"

          resources:
            requests:
              cpu: 5m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 192Mi

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20

          volumeMounts:
            - name: datasource
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: true

            - name: dashboard-provider
              mountPath: /etc/grafana/provisioning/dashboards
              readOnly: true

            - name: dashboard
              mountPath: /var/lib/grafana/dashboards
              readOnly: true

            - name: grafana-data
              mountPath: /var/lib/grafana

      volumes:
        - name: datasource
          configMap:
            name: grafana-datasource

        - name: dashboard-provider
          configMap:
            name: grafana-dashboard-provider

        - name: dashboard
          configMap:
            name: grafana-dashboard-chay-api

        - name: grafana-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app: grafana
  ports:
    - name: http
      port: 3000
      targetPort: http
