global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: chay-demo-api
    metrics_path: /metrics
    static_configs:
      - targets:
          - chay-demo-api.chay-devsecops.svc.cluster.local:80
